### ISSUE TITLE
Full training + Specific test set not working

### ISSUE THREAD

**Issue by jonjoncardoso** [enanomapper/RRegrs#20]
# Hi,

I'm trying to use RRegrs to perform full training on training samples and I'd like to use it to validate the results on a specific test set I have. I have two data frames `train.df` and `test.df`, I renamed the first column of each one of them to `net.c`, otherwise it wouldn't work, but when I run: 

`RRegrs::LMreg(train.df,test.df,sCV="none")`

I get an error:

`Error in $<-.data.frame(*tmp*, "method", value = "lm") : 
  replacement has 1 row, data has 0`

By inspection, I noticed this happens because since I set `sCV` to `none`, it is full training therefore `lm.fit$results` returns an empty data.frame. The metrics RMSE and R2 would have to be calculated manually using `caret::RMSE` and `caret::R2` in this case.

**Comment by GTsiliki** [comment]
Hello,

Good point; we haven't tested it with sCV='none', since the purpose of the tool is to produce fully validated models and that's why the options for CVtypes in RRegrs function are "repeatedcv;LOOCV".

Concerning caret::RMSE,R2 functions, since adjR^2 is not an option in caret, we are including in-house functions for RMSE,R2 stats, but of course they could be used.

**Comment by jonjoncardoso** [comment]
On a second thought, maybe there is no point in implementing full training. I guess I could just use repeated Cross-Validation passing my `test.df` data frame as an external validation anyway.

**Comment by GTsiliki** [comment]
Sure, that should work fine
